import {mkdir, writeFile} from 'node:fs/promises';
const out = new URL('../dist/', import.meta.url);
await mkdir(out,{recursive:true});
const booking='https://www.hotpepper.jp/strJ004072002/';
const instagram='https://www.instagram.com/kusiage.rohan/';
const map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('串揚げと魚 ろはん いわき');
const ext='target="_blank" rel="noopener noreferrer"';
const arrow='<span aria-hidden="true">↗</span>';
const ig='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>';
const brand='<span>串揚げと魚</span><strong>ろはん</strong>';
const links=[['index.html#story','ろはんのこと'],['menu.html','お品書き'],['space.html','店内のご案内'],['access.html','店舗案内']];
const nav=page=>links.map(([href,label])=>`<a href="${href}"${href===page?' aria-current="page"':''}>${label}</a>`).join('');
const header=page=>`<a class="skip" href="#main">本文へ</a><header class="site-header"><a class="brand" href="index.html" aria-label="串揚げと魚 ろはん トップ">${brand}</a><nav aria-label="メインナビゲーション">${nav(page)}</nav><a class="reserve" href="${booking}" ${ext}>お席のご予約 ${arrow}</a><button class="menu-toggle" type="button" aria-label="メニューを開く" aria-controls="mobile-menu" aria-expanded="false"><span></span><span></span><small>MENU</small></button></header><dialog id="mobile-menu" aria-labelledby="mobile-menu-title"><div class="dialog-head"><p id="mobile-menu-title">串揚げと魚 ろはん</p><button type="button" class="menu-close" aria-label="メニューを閉じる">閉じる ×</button></div><nav aria-label="スマートフォンメニュー"><a href="index.html">トップ</a>${nav(page)}</nav><a class="button" href="${booking}" ${ext}>お席を予約する ${arrow}</a><a class="dialog-phone" href="tel:0246253175">0246-25-3175</a><p>17:00–22:00 ／ 月・日 定休</p></dialog>`;
const reservation=`<section class="reservation section" id="reservation"><div><p class="eyebrow">RESERVATION</p><h2>今夜は、ろはんへ。</h2><p>お席のご予約は、ネットまたはお電話で。<br>おひとりの一杯も、大切な人との食事も。</p></div><div class="reservation-actions"><a class="button" href="${booking}" ${ext}>空席確認・ネット予約 ${arrow}</a><a class="phone" href="tel:0246253175"><span>お電話でのご予約</span>0246-25-3175</a><p class="note">全席喫煙可のため、20歳未満の方はご入店いただけません。</p></div></section>`;
const footer=page=>`<footer class="footer"><div class="footer-top"><a class="brand" href="index.html" aria-label="串揚げと魚 ろはん トップ">${brand}</a><div><p>〒970-8026 福島県いわき市田町14-3</p><p>17:00–22:00 ／ 月・日 定休</p></div><a class="social-link" href="${instagram}" ${ext}>${ig}Instagram ${arrow}</a></div><div class="footer-bottom"><nav aria-label="フッターナビゲーション">${nav(page)}</nav><small>© 串揚げと魚 ろはん</small></div></footer><div class="mobile-actions"><a href="tel:0246253175">電話する</a><a href="${booking}" ${ext}>お席を予約 ${arrow}</a></div>`;
const dims={sashimi:[1200,675],table:[1200,675],karaage:[1200,675],'oden-pot':[1200,900],gyoza:[1200,675],oden:[960,1706],kushi:[960,1706],counter:[960,1706],soda:[960,1706],parfait:[960,1706]};
function photo(name,alt,cls='',eager=false){const [w,h]=dims[name];return `<img class="${cls}" src="assets/${name}-1200.webp" srcset="assets/${name}-640.webp 640w, assets/${name}-1200.webp ${w}w" sizes="(max-width: 760px) 100vw, 60vw" width="${w}" height="${h}" alt="${alt}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
function head(title,desc){return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#202926"><title>${title}｜串揚げと魚 ろはん</title><meta name="description" content="${desc}"><meta property="og:title" content="${title}｜串揚げと魚 ろはん"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='8' fill='%23202926'/%3E%3Ctext x='32' y='47' text-anchor='middle' fill='%23f7f3eb' font-size='47' font-family='serif'%3Eろ%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/pages.css"><script src="assets/site.js" defer></script></head>`;}
const page=(filename,title,desc,body)=>writeFile(new URL(filename,out),head(title,desc)+`<body>${header(filename)}<main id="main">${body}${reservation}</main>${footer(filename)}</body></html>`);
const subhead=(en,title,copy)=>`<div class="page-heading"><p class="eyebrow">${en}</p><h1>${title}</h1><p>${copy}</p></div>`;
const rows=items=>`<dl class="menu-list">${items.map(([n,p])=>`<div><dt>${n}</dt><dd>${p}</dd></div>`).join('')}</dl>`;
const foodGroups=[
 ['kushi','串揚げ',[['豚ヒレ','250円'],['エビ','250円'],['イカ','250円'],['ハムカツ','180円'],['うずら','180円'],['にんにく','180円'],['しいたけ','180円'],['山芋','180円'],['なす','160円']]],
 ['fish','お刺身',[['選べる三種盛り','1,500円'],['カツオ','980円'],['イカ','800円'],['サーモン','800円'],['マグロ','900円'],['マダイ','900円']]],
 ['oden','おでん',[['大根','150円'],['たまご','150円'],['ちくわ','150円'],['はんぺん','150円'],['しらたき','150円'],['もち袋','250円'],['牛スジ','350円']]],
 ['alacarte','一品料理',[['手作りギョーザ','450円'],['鶏唐揚げ','550円'],['ポテトフライ','450円'],['ゲソ揚げ','550円'],['タコ唐揚げ','500円'],['軟骨揚げ','500円'],['じゃが芋ピザ','400円']]],
 ['salad','サラダ・おつまみ',[['野菜サラダ','550円'],['生ハムサラダ','780円'],['漬物','400円'],['冷奴','350円'],['なめ茸おろし','400円'],['しらすおろし','400円'],['ところてん・枝豆・モロキュー・梅キュー・もずく酢','各380円']]],
 ['finish','お食事・甘味',[['お茶漬け・おにぎり（漬物付）','各500円'],['かけそば','500円'],['バニラアイス','350円'],['チョコバナナパフェ','730円']]]
];
await page('index.html','いわきの、いつもの一軒。','いわき駅から徒歩5分。揚げたての串揚げ、旬の魚、9月から5月のおでん。串揚げと魚 ろはんで、心ほどけるひとときを。',`
<section class="hero"><div class="hero-photo">${photo('sashimi','ろはんの彩り豊かなお刺身盛り合わせ','',true)}</div><div class="hero-text"><p class="eyebrow">IWAKI, FUKUSHIMA</p><h1>揚げたてのひと串。<br>旬を味わう、一献。</h1><p class="hero-copy">おいしい料理と、何気ない会話。<br>今日の終わりに、ふらりと「ろはん」へ。</p><a class="line-link" href="#story">ろはんのこと <span aria-hidden="true">↓</span></a></div><div class="hero-bottom"><span>串揚げ・旬の魚・おでん</span><span>いわき駅 徒歩5分 <i></i> 17:00—22:00</span></div><p class="hero-side">心ほどける、いつもの一軒。</p></section>
<section class="story section" id="story"><div class="story-picture reveal">${photo('counter','木のカウンターが続く、ろはんの店内')}<span class="picture-label">いつでも、帰ってこられる場所。</span></div><div class="story-copy reveal"><p class="eyebrow">OUR STORY</p><h2>変わらない味。<br>つながる、ひととき。</h2><p>料理を楽しみに。会話を楽しみに。<br>お店が変わっても、また足を運んでくださる。<br>そんなお客様とのつながりを、<br>何より大切にしています。</p><p>いつもの一杯も、初めてのひと皿も。<br>あなたにとって「また来たい」と思える場所に。</p><a class="line-link" href="space.html">ろはんの空間を見る <span aria-hidden="true">→</span></a></div></section>
<section class="food-section section" id="food"><div class="section-title reveal"><div><p class="eyebrow">THE TASTE OF ROHAN</p><h2>今夜を、おいしく。</h2></div><a class="line-link" href="menu.html">お品書きを見る <span aria-hidden="true">→</span></a></div><div class="food-grid"><a class="food-card reveal" href="menu.html#kushi"><figure>${photo('kushi','生ビールと枝豆に添えた、揚げたての豚ヒレ串')}</figure><div><span class="number">01</span><h3>香ばしい、ひと串。</h3><p>揚げたての串揚げを、お好きな一杯と。</p><span class="card-link">串揚げ <span aria-hidden="true">→</span></span></div></a><a class="food-card reveal" href="menu.html#fish"><figure>${photo('sashimi','まぐろ、サーモンなどを彩りよく盛り付けたお刺身')}</figure><div><span class="number">02</span><h3>旬を、少しずつ。</h3><p>魚のおいしさを、まっすぐお刺身で。</p><span class="card-link">旬の魚 <span aria-hidden="true">→</span></span></div></a><a class="food-card reveal" href="menu.html#oden"><figure>${photo('oden','出汁が染み込んだ大根、玉子、もち袋などのおでん')}</figure><div><span class="number">03</span><h3>ほっとする、ひと皿。</h3><p>親しまれてきた味を、ろはんでも。</p><span class="card-link">おでん〈9月–5月〉 <span aria-hidden="true">→</span></span></div></a></div></section>
<section class="oden-feature"><div class="oden-picture reveal">${photo('oden-pot','カウンターでじっくり温めるろはんのおでん鍋')}</div><div class="oden-copy reveal"><p class="eyebrow">A TASTE TO COME HOME TO</p><p class="season-label">九月から五月まで</p><h2>懐かしい味が、<br>またひとつ。</h2><p>以前のお店で親しまれていたおでんを、ろはんでも。じっくり味を染み込ませた一品は、お酒のお供にも、ほっと一息つきたい夜にも。</p><p>ご存じの方には、懐かしい味を。<br>初めての方には、これからの馴染みの味を。</p><a class="line-link" href="menu.html#oden">おでんのお品書き <span aria-hidden="true">→</span></a></div></section>
<section class="space-teaser section" id="space"><div class="section-title reveal"><div><p class="eyebrow">OUR SPACE</p><h2>肩の力を抜いて、<br>ゆっくりと。</h2></div><div><p>おひとりならカウンターへ。<br>気の置けない人とは、テーブルを囲んで。</p><a class="line-link" href="space.html">店内のご案内 <span aria-hidden="true">→</span></a></div></div><a href="space.html" class="wide-space reveal">${photo('table','温かな木のテーブルと黄色い座面の椅子が並ぶろはんのテーブル席')}<span>木の温もりに、くつろぐ。</span></a></section>
<section class="instagram-section section" id="instagram"><div class="instagram-title reveal">${ig}<p class="eyebrow">INSTAGRAM</p><h2>ろはんの、日々。</h2><p>その日のおすすめや、お店からのお知らせを。</p><a class="line-link" href="${instagram}" ${ext}>@kusiage.rohan ${arrow}</a></div><div class="instagram-images"><a href="${instagram}" ${ext} aria-label="ろはんのInstagramで料理を見る">${photo('gyoza','ろはんの手作りギョーザ')}</a><a href="${instagram}" ${ext} aria-label="ろはんのInstagramで甘味を見る">${photo('parfait','チョコバナナパフェ')}</a><a href="${instagram}" ${ext} aria-label="ろはんのInstagramでお知らせを見る">${photo('soda','彩りのよいクリームソーダ')}</a></div></section>`);
await page('menu.html','お品書き','串揚げ、旬のお刺身、9月から5月のおでん。ろはんの料理とお飲み物をご紹介します。',`
${subhead('OUR MENU','お品書き','好きなものを、好きなだけ。<br>今夜の一杯とともに。')}
<section class="menu-feature section"><div class="menu-feature-image reveal">${photo('kushi','ビール、枝豆、豚ヒレ串を楽しむちょい飲みセット','',true)}</div><div class="menu-feature-copy reveal"><p class="eyebrow">A LITTLE DRINK, A GOOD EVENING</p><h2>まずは、<br>ちょっと一杯。</h2><h3>ちょい飲みセット</h3><p>生ビール中 1杯・豚ヒレ串 1本・枝豆</p><p class="price">800<span>円（税込）</span></p><p>一日の終わりに、ひと息。<br>お仕事帰りにも、二軒目にもどうぞ。</p></div></section>
<nav class="menu-index" aria-label="お品書きのカテゴリー">${foodGroups.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}<a href="#drink">お飲み物</a></nav>
<section class="menu-content section"><p class="note menu-note">価格はすべて税込です。仕入れや季節により、内容が変わる場合がございます。</p><div class="menu-columns">${foodGroups.map(([id,title,items],i)=>`<section class="menu-group reveal" id="${id}"><p class="eyebrow">0${i+1}</p><h2>${title}</h2>${id==='oden'?'<p class="tagline">9月〜5月の季節限定</p>':''}${rows(items)}${id==='fish'?'<p class="note">三種盛りは、単品のお刺身からお選びください。写真は盛り付けの一例です。</p>':''}${id==='finish'?'<p class="note">お茶漬け・おにぎりは梅・鮭・明太子からお選びください。</p>':''}</section>`).join('')}</div><p class="source-note">メニュー掲載情報：2026年9月確認。<a href="${booking}food/" ${ext}>最新のお品書き ${arrow}</a></p></section>
<section class="drink-section section" id="drink"><div class="drink-copy reveal"><p class="eyebrow">DRINKS</p><h2>料理に寄り添う、<br>お好きな一杯。</h2><p>ビール、日本酒、焼酎、ハイボール。<br>その日の気分で、お楽しみください。</p>${rows([['生ビール（アサヒスーパードライ 中）','650円'],['ハイボール（ブラックニッカ）','550円'],['澤の鶴 一合（冷・熱燗）','500円'],['梅酒','550円'],['アサヒドライゼロ','450円']])}<a class="line-link" href="${booking}drink/" ${ext}>お飲み物の全メニュー ${arrow}</a></div><div class="drink-image reveal">${photo('soda','ろはんのクリームソーダ')}</div></section>`);
await page('space.html','店内のご案内','木の温もりを感じる、いわきの小さな一軒。ろはんのカウンター席とテーブル席をご紹介します。',`
${subhead('A PLACE TO UNWIND','店内のご案内','いつもの一杯を、いつものように。<br>初めての方も、気負わずに。')}
<div class="space-banner">${photo('table','木目を基調としたろはんのテーブル席','',true)}</div>
<section class="space-story section"><div class="reveal"><p class="eyebrow">AT THE COUNTER</p><h2>料理と会話が、<br>ちょうどいい距離に。</h2><p>ひとりでふらりと立ち寄る夜も。<br>おいしいものを囲んで語らう夜も。</p><p>木の温もりに包まれた、肩ひじ張らない場所。<br>料理はもちろん、人とのつながりも楽しんでいただけたら。<br>そんな気持ちで、お迎えしています。</p></div><figure class="counter-detail reveal">${photo('counter','おひとりでも過ごしやすいろはんのカウンター席')}<figcaption>カウンター席</figcaption></figure></section>
<section class="table-section section"><figure class="reveal">${photo('table','友人同士の食事に使える木のテーブル席')}<figcaption>テーブル席</figcaption></figure><div class="reveal"><p class="eyebrow">AROUND THE TABLE</p><h2>おいしい時間を、<br>分かち合う。</h2><p>親しい人との食事や、仕事終わりの集まりに。<br>同じテーブルを囲む時間を、ゆっくりとお楽しみください。</p><p>貸切のご相談も承ります。<br>ご利用人数など、まずはお電話でお聞かせください。</p><a class="line-link" href="tel:0246253175">電話で相談する <span aria-hidden="true">→</span></a></div></section>
<aside class="visit-note"><h2>ご来店前に</h2><p>当店は全席喫煙可能です。<br>20歳未満の方は、同伴の場合もご入店いただけません。</p></aside>`);
await page('access.html','店舗案内・ご予約','いわき駅から徒歩5分。串揚げと魚 ろはんのアクセス、営業時間、ご予約のご案内。電話0246-25-3175。',`
${subhead('ACCESS & INFORMATION','店舗案内','いわき駅から徒歩5分。<br>今夜は、ろはんへ。')}
<section class="access-section section"><div class="access-photo reveal"><img src="assets/exterior.webp" width="1200" height="900" alt="串揚げと魚 ろはんの看板が掲げられたお店の入口" fetchpriority="high"><a class="button map-link" href="${map}" ${ext}>Google マップで道順を見る ${arrow}</a></div><div class="access-info reveal"><p class="eyebrow">KUSHIAGE & SAKANA ROHAN</p><h2>串揚げと魚 ろはん</h2><dl class="info-list"><div><dt>所在地</dt><dd>〒970-8026<br>福島県いわき市田町14-3</dd></div><div><dt>アクセス</dt><dd>いわき駅から徒歩5分（約260m）</dd></div><div><dt>営業時間</dt><dd>17:00–22:00<br><span>料理 L.O. 21:30<br>ドリンク L.O. 22:00</span></dd></div><div><dt>定休日</dt><dd>月曜日・日曜日</dd></div><div><dt>電話番号</dt><dd><a href="tel:0246253175">0246-25-3175</a></dd></div><div><dt>駐車場</dt><dd>なし</dd></div><div><dt>喫煙について</dt><dd>全席喫煙可<br><span>20歳未満の方は同伴の場合も入店不可</span></dd></div></dl><p class="note">臨時休業などのお知らせはInstagramをご覧ください。</p><a class="line-link" href="${instagram}" ${ext}>Instagramでお知らせを見る ${arrow}</a></div></section>`);
await writeFile(new URL('404.html',out),head('ページが見つかりません','串揚げと魚 ろはんのトップページへ。')+`<body>${header('')}<main id="main" class="error-page section"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>ページが見つかりません。</h1><p>お探しのページは移動、または削除された可能性があります。</p><a class="button" href="index.html">トップページへ</a></main>${footer('')}</body></html>`);
console.log('Built: index.html, menu.html, space.html, access.html, 404.html');
